vtex-sites/storecomponents.store

lighthouserc.json

I've removed assertions to setup lighthouse-ci correctly. Now I'm adding them back

Adds assertions back

---

README.md

Tries improving the readme a little bit. However, it's still a long way to go

Improves the readme

---

lighthouserc.json

improve lighthouse-ci config

---

package.json
yarn.lock

Resolve proxy in Netlify

---

gatsby-config.js
lighthouserc.js
package.json
yarn.lock

Adds CMS integration via local-storage API

CMS integration

---

package.json
src/gatsby-plugin-theme-ui/index.ts
yarn.lock

using the new design partner to store components

Theme organization

---

package.json
src/gatsby-plugin-theme-ui/index.ts
yarn.lock

Reverts vtex-sites/storecomponents.store#110

Revert "add rich texts to home"

---

.github/workflows/main.yml
.github/workflows/merge.yml

This PR points the lighthouse CI Server to VTEX

Uses lighthouse ci server from VTEX

---

package.json
yarn.lock

This pr adds progress bar for slow pages

Adds progress bar

---

package.json
yarn.lock

Adds product preview for dinamic pages

Product Preview

---

i18n/messages/en.json
i18n/messages/pt.json
package.json
src/@vtex/gatsby-plugin-theme-ui/custom.ts
yarn.lock

Shelf slider

---

pull_request_template.md

We believe that documentation is essential for an educated decision flow — to internal and partner's developers. This is an invitation to share the whys and make everybody an owner of the motivation and possibilities.
Today our technical writing team needs to investigate the technologies we use to create features, components, protocols, and etc. It takes time and VTEX's TW team is small nowadays. 
We are also close to the Fast Store open beta reality and we need to provide independence for our partner's developers to work with this new workflow.
It's a template with tips about what to write in each section. The main goal is to make us all go beyond the descriptions and start to explain more.
Use it and send feedback to @VictoriaMolgado (@molgado on Slack).
- Does it fit in your daily …

documentation-template

---

gatsby-config.js
package.json
yarn.lock

My account

---

README.md

Just a test to see if we are correctly generating a full deploy preview when a merge in master happens

test merge on master pipeline

---

package.json
src/@vtex/gatsby-theme-vtex/components/BuyButton.tsx
yarn.lock

This PR adds a loading state (Spinner) to buy button to give a visual feedback to the user when adding to cart.

Buy button on loading state

---

README.md

test lhci run in master

---

package.json
yarn.lock

Some Performance Improvements

---

src/@vtex/gatsby-theme-vtex/components/HomePage/carousel.json

Our score in calibre is being harmed because, somehow, calibre motoG4 os wider than our media queries for smartphones. this PR fixes this problem by using the right media query

upgrade media query

---

package.json
yarn.lock

GraphQL Cache

---

package.json
src/@vtex/gatsby-theme-vtex/components/BuyButton.tsx
yarn.lock

- Breaking change on theme's at `1.125.0`

Changing useBuyButton call

---

package.json
src/@vtex/gatsby-theme-vtex/components/ProductPage/Above/Async/index.tsx
yarn.lock

SKU Selector support

---

gatsby-config.js
package.json
yarn.lock

@vtex/gatsby-plugin-nginx

---

package.json
yarn.lock

Gtm configurable

---

package.json
yarn.lock

Fix orderForm inconsistency

---

package.json
yarn.lock

Use new contentType.json format

---

package.json
yarn.lock

404 status code on notFound page

---

package.json
yarn.lock

CMS Plugin using GraphQL Tools

---

gatsby-config.js
package.json
yarn.lock

Use new CMS API

---

package.json
src/@vtex/gatsby-plugin-cms/fixtures/home.json
yarn.lock

Use new CMS Fixtures API

---

package.json
yarn.lock

Error handler in page wrapper

---

package.json
src/@vtex/gatsby-plugin-theme-ui/base.ts
src/@vtex/gatsby-plugin-theme-ui/searchFilter.ts
src/@vtex/gatsby-theme-store/components/HomePage/SEO.tsx
src/@vtex/gatsby-theme-store/components/HomePage/__generated__/HomePageSEOQuery.graphql.ts
src/@vtex/gatsby-theme-store/components/ProductPage/Above/Async/index.tsx
src/@vtex/gatsby-theme-store/components/ProductPage/AboveTheFold.tsx
src/@vtex/gatsby-theme-store/components/ProductSummary/index.tsx
src/@vtex/gatsby-theme-store/pages/__generated__/HomePageQuery.graphql.ts
yarn.lock

Our Sonarqube pipeline is triggering some errors and warnings about Typescript ESLint issues, those changes will fix them.
Those pipelines happens in our store projects. So, we can check if the pipeline will fail in this PR or [Marin Brasil PR](https://github.com/vtex-sites/marinbrasil.store/pull/289).
[Faststore Fix](https://github.com/vtex/faststore/pull/468)

fix Sonarqube/Lint pipelines

---

package.json
yarn.lock

noindex in account/login page

---

package.json
yarn.lock

Fix nprogress

---

gatsby-config.js
package.json
src/@vtex/gatsby-theme-store/components/HomePage/__generated__/HomePageSEOQuery.graphql.ts
src/@vtex/gatsby-theme-store/pages/__generated__/HomePageQuery.graphql.ts
staticPaths.json
yarn.lock

This PR uses the newly exported staticPaths function from `@vtex/gatsby-source-vtex` to generate the staticPaths. This function exports all category paths along with the best selling products to statically generate the most importante pages
Uses the newly exported staticPaths when `NODE_ENV` is `production`. Uses `staticPaths.json` when running `yarn develop`

Static Paths

---

package.json

Update nginx plugin to enable brotli

---

gatsby-config.js

SEO | Disallow no indexable paths in robots

---

package.json
yarn.lock

This PR adds breadcrumb to the product page

SEO | Product Breadcrumb 

---

package.json
yarn.lock

Fix | SWR defaults

---

src/@vtex/gatsby-plugin-theme-ui/searchBanner.ts
src/@vtex/gatsby-theme-store/components/SearchPage/Banner.tsx

This PR hacks lighthouse so it doesn't complain about low resolutions on mobile. Also this PR improves LCP by rendering a low res image to low power devices. and hight res to beefier devices.

Improve LCP from banner in search page

---

package.json
src/@vtex/gatsby-theme-store/pages/__generated__/HomePageQuery.graphql.ts
yarn.lock

[FastStore](https://github.com/vtex/faststore/pull/515)

Fixing circular dependencies from store-ui

---

gatsby-config.js

Remove Set-Cookie

---

gatsby-config.js

page-data was preventing google bot from rendering the page. This PR fixes this issue

Fix robots txt

---

package.json
yarn.lock

Fix via for orderPlaced

---

src/@vtex/gatsby-plugin-theme-ui/searchBanner.ts
src/@vtex/gatsby-plugin-theme-ui/slider.ts

Fix cls desktop

---

package.json
yarn.lock

Housekeeper

---

package.json
yarn.lock

Reduce TBT

---

package.json
yarn.lock

Remove orderForm "mudinho"

---

package.json
yarn.lock

Fix infinite loop

---

package.json
src/@vtex/gatsby-theme-store/components/ProductPage/SEO/__generated__/StoreProductPageSEOQuery.graphql.ts
src/@vtex/gatsby-theme-store/components/SearchPage/SEO/__generated__/StoreSearchPageSEOQuery.graphql.ts
src/@vtex/gatsby-theme-store/pages/__generated__/HomePageQuery.graphql.ts
yarn.lock

Fix | Query changes

---

package.json
yarn.lock

It adds `gatsby-plugin-i18n` as an explicit dependency to avoid text editors complaining about not finding imports from this dependency and also avoiding headaches with symlinks.

Explicit gatsby-i18n dependency

---

.github/dependabot.yml

Setting "automerge" label for dependabot

---

src/@vtex/gatsby-theme-store/components/ProductPage/Above/Async/Offer.tsx
src/@vtex/gatsby-theme-store/components/ProductPage/Above/Async/index.tsx

As it says on the tin
Mimics this PR, reflecting its change on the default theme https://github.com/vtex-sites/carrefourbrfood.store/pull/188

Hide buy button if available quantity is 0

---

src/@vtex/gatsby-plugin-theme-ui/productSummary.ts

Summary display

---

src/components/SearchBar/index.tsx

Search is breaking due to the Suspense component that was being imported from @vtex/store-ui.
Try to use the search

Fix search brearking due to Suspense

---

vtex.env

Use node_modules cache

---

src/@vtex/gatsby-plugin-cms/index.ts

fix orderBy

---

src/@vtex/gatsby-plugin-theme-ui/custom.ts
src/components/common/RichTextRow/deal.md
src/components/common/RichTextRow/delivery.md
src/components/common/RichTextRow/free-shipping.md
src/components/common/RichTextRow/index.tsx
src/components/common/RichTextRow/pickup.md
src/components/common/RichTextRow/styles.json

Local Styles

---

src/@vtex/gatsby-plugin-cms/index.ts

Adding RichText and banners for Demo
